---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  channel: stable
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  # Manual approval for install plans - enables version control via GitOps
  installPlanApproval: Manual
  # Pin to specific version v1.15.0
  startingCSV: cert-manager.v1.15.2

