---
# CronJob to automatically approve pending InstallPlans
# Runs every 5 minutes to check for pending approvals
apiVersion: batch/v1
kind: CronJob
metadata:
  name: installplan-approver
  namespace: gitlab-runner-operator
  annotations:
    # This IS managed by GitOps - it's idempotent
    argocd.argoproj.io/sync-wave: "0"
spec:
  schedule: "*/15 * * * *"  # Every 15 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600  # Clean up after 10 minutes
      template:
        metadata:
          labels:
            app: installplan-approver
        spec:
          serviceAccountName: installplan-approver
          restartPolicy: Never
          containers:
            - name: approver
              image: registry.redhat.io/openshift4/ose-cli:latest
              command:
                - /bin/bash
                - -c
                - |
                  set -e
                  echo "Checking for pending InstallPlans..."
                  
                  # Get all pending install plans
                  PENDING_IPS=$(oc get installplan -n gitlab-runner-operator \
                    -o jsonpath='{range .items[?(@.spec.approved==false)]}{.metadata.name}{"\n"}{end}')
                  
                  if [ -z "$PENDING_IPS" ]; then
                    echo "No pending InstallPlans found. Nothing to do."
                    exit 0
                  fi
                  
                  echo "Found pending InstallPlans:"
                  echo "$PENDING_IPS"
                  
                  for IP in $PENDING_IPS; do
                    echo "Approving InstallPlan: $IP"
                    oc patch installplan "$IP" -n gitlab-runner-operator \
                      --type merge \
                      --patch '{"spec":{"approved":true}}'
                    
                    if [ $? -eq 0 ]; then
                      echo "Successfully approved InstallPlan: $IP"
                    else
                      echo "Failed to approve InstallPlan: $IP"
                      exit 1
                    fi
                  done
                  
                  echo "All pending InstallPlans approved!"

