---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager-operator
  annotations:
    config.kubernetes.io/description: "Red Hat cert-manager Operator for Red Hat OpenShift"

# Set default namespace for all resources
namespace: cert-manager-operator

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/managed-by: openshift-gitops

