---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: "openshift-gitops"
  channel: gitops-1.18
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # Manual approval for install plans
  installPlanApproval: Manual
  # Pin to specific version - update as needed
  startingCSV: openshift-gitops-operator.v1.18.1

