---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  labels:
    app: openshift-gitops-operator
  annotations:
    # Prevent ArgoCD from deleting this namespace when operator Application is removed
    argocd.argoproj.io/sync-options: Delete=false

