---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-operator-group
  namespace: openshift-gitops-operator
spec:
  # Empty targetNamespaces means watch all namespaces
  targetNamespaces: []

