---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay: cert-manager with InstallPlanApprover
# This combines:
#   - Base cert-manager subscription (with Manual installPlanApproval)
#   - InstallPlanApprover CR (for automatic approval of version-matched InstallPlans)
#
# The InstallPlanApprover operator will automatically approve the InstallPlan
# ONLY if the CSV version matches the Subscription's startingCSV.

resources:
  - ../../base
  - installplanapprover.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/managed-by: kustomize
      automation: installplan-approver

